// app/page.tsx  (or pages/index.tsx)
'use client';

import dynamic from 'next/dynamic';
import { useState } from 'react';
import 'mapbox-gl/dist/mapbox-gl.css';

const Map = dynamic(() => import('@vis.gl/react-mapbox').then(m => m.Map), {
  ssr: false,
});

type Flight = {
  origin: string;
  destination: string;
  distance?: number;
  summary?: string;
};

export default function Home() {
  const [flights, setFlights] = useState<Flight[]>([]);
  const [form, setForm] = useState({ origin: '', destination: '' });
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/insight`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      });
      const data = await res.json();
      setFlights(prev => [...prev, { ...form, summary: data.summary }]);
      setForm({ origin: '', destination: '' });
    } finally {
      setLoading(false);
    }
  }

  const token = process.env.NEXT_PUBLIC_MAPBOX_TOKEN;

  return (
    <main className="flex flex-col items-center min-h-screen bg-slate-950 text-white p-6">
      <h1 className="text-3xl font-bold mb-4">Flight Log Visualizer ✈️</h1>

      <form onSubmit={handleSubmit} className="flex gap-2 mb-6 bg-slate-800 p-4 rounded-xl shadow-lg">
        <input
          type="text"
          placeholder="Origin (e.g., TPA)"
          value={form.origin}
          onChange={(e) => setForm({ ...form, origin: e.target.value.toUpperCase() })}
          className="p-2 rounded text-black"
          required
        />
        <input
          type="text"
          placeholder="Destination (e.g., HND)"
          value={form.destination}
          onChange={(e) => setForm({ ...form, destination: e.target.value.toUpperCase() })}
          className="p-2 rounded text-black"
          required
        />
        <button type="submit" disabled={loading} className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded text-white font-semibold">
          {loading ? 'Generating...' : 'Add Flight'}
        </button>
      </form>

      <div className="w-full max-w-5xl h-[400px] mb-6 rounded-xl overflow-hidden border border-slate-700">
        {token ? (
          <Map
            mapboxAccessToken={token}
            mapStyle="mapbox://styles/mapbox/dark-v11"
            initialViewState={{ longitude: 0, latitude: 20, zoom: 1 }}
            style={{ width: '100%', height: '100%' }}
          />
        ) : (
          <div className="flex items-center justify-center h-full text-sm text-red-300">
            Missing NEXT_PUBLIC_MAPBOX_TOKEN
          </div>
        )}
      </div>

      <div className="max-w-3xl w-full">
        {flights.length === 0 ? (
          <p className="text-gray-400 text-center">No flights logged yet.</p>
        ) : (
          flights.map((f, idx) => (
            <div key={idx} className="bg-slate-800 rounded-xl p-4 mb-4 border border-slate-700">
              <h2 className="text-xl font-semibold">{f.origin} → {f.destination}</h2>
              <p className="text-sm text-gray-400 mt-1">Generated by Gemini ✳️</p>
              <p className="mt-2">{f.summary}</p>
            </div>
          ))
        )}
      </div>
    </main>
  );
}