/* AUTO-GENERATED FILE — DO NOT EDIT
   * Generated by: scripts/generatePhotoIndex.mjs
   */

export type PhotoItem = { src: string; caption?: string; date?: string };

export const CITY_BY_AIRPORT: Record<string, string> = {
  "IAD": "Washington-DC",
  "ORD": "Chicago",
  "PHL": "Philadelphia",
  "SEA": "Seattle",
  "BNA": "Nashville",
  "SDF": "Louisville",
  "SJU": "San-Juan",
  "IND": "Indianapolis",
  "TPA": "Tampa",
  "EZE": "Buenos-Aires",
  "SCL": "Santiago",
  "LIM": "Lima",
  "MVD": "Montevideo",
  "AQP": "Arequipa",
  "CUZ": "Cusco",
  "LHR": "London",
  "BCN": "Barcelona",
  "EDI": "Edinburgh",
  "CDG": "Paris",
  "ZAG": "Zagreb",
  "VCE": "Venice",
  "BZO": "Bolzano",
  "LJU": "Ljubljana",
  "NCE": "Nice",
  "MRS": "Marseille",
  "MAD": "Madrid",
  "BUD": "Budapest",
  "HAN": "Hanoi",
  "BKK": "Bangkok",
  "SGN": "Ho-Chi-Minh-City",
  "REP": "Siem-Reap",
  "PNH": "Phnom-Penh",
  "DAD": "Da-Nang"
} as const;

export const PHOTO_INDEX: Record<string, PhotoItem[]> = {
  "IAD": [],
  "ORD": [],
  "PHL": [],
  "SEA": [],
  "BNA": [],
  "SDF": [
    {
      "src": "/photos/Louisville/1-30-26-salamanca.jpg",
      "caption": "1 30 26 salamanca",
      "date": null
    }
  ],
  "SJU": [],
  "IND": [],
  "TPA": [],
  "EZE": [],
  "SCL": [],
  "LIM": [],
  "MVD": [],
  "AQP": [],
  "CUZ": [],
  "LHR": [],
  "BCN": [],
  "EDI": [],
  "CDG": [],
  "ZAG": [],
  "VCE": [],
  "BZO": [],
  "LJU": [],
  "NCE": [],
  "MRS": [],
  "MAD": [
    {
      "src": "/photos/Madrid/atletico-game.jpg",
      "caption": "atletico game",
      "date": null
    }
  ],
  "BUD": [],
  "HAN": [],
  "BKK": [],
  "SGN": [],
  "REP": [],
  "PNH": [],
  "DAD": []
};

export function getCityForAirport(code: string) {
  return CITY_BY_AIRPORT[code] ?? null;
}

export function getPhotosForAirport(code: string): PhotoItem[] {
  return PHOTO_INDEX[code] ?? [];
}
