export type CountryPhoto = {
  file: string;
  caption?: string;
  locationId?: string;
  locationLabel?: string;
  date?: string;
  cover?: boolean;
};

export type CountryPhotoAlbum = {
  folder: string;
  photos: CountryPhoto[];
};

// Example:
// Spain: {
//   folder: "spain",
//   photos: [
//     {
//       file: "atletico-game.jpg",
//       caption: "Atletico game",
//       locationId: "madrid",
//       locationLabel: "Madrid",
//       cover: true,
//     },
//   ],
// },
export const COUNTRY_PHOTO_ALBUMS: Record<string, CountryPhotoAlbum> = {
  Albania: {
    folder: "albania",
    photos: [
      { file: "IMG_3469.JPG", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026", cover: true },
      { file: "IMG_3484.JPG", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026" },
      { file: "IMG_5231.JPG", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026" },
      { file: "IMG_6705.jpg", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026" },
      { file: "IMG_6706.jpg", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026" },
      { file: "IMG_6710.jpg", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026" },
      { file: "IMG_6711.jpg", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026" },
      { file: "IMG_6718.jpg", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026" },
      { file: "IMG_6720.jpg", locationId: "tirana", locationLabel: "Tirana", caption: "March 2026" },
      { file: "IMG_3546.JPG", locationId: "berat", locationLabel: "Berat", caption: "March 2026" },
      { file: "IMG_6737.jpg", locationId: "berat", locationLabel: "Berat", caption: "March 2026" },
      { file: "IMG_6746.jpg", locationId: "berat", locationLabel: "Berat", caption: "March 2026" },
      { file: "IMG_6747.jpg", locationId: "berat", locationLabel: "Berat", caption: "March 2026" },
      { file: "IMG_6752.jpg", locationId: "berat", locationLabel: "Berat", caption: "March 2026" },
      { file: "IMG_6760.jpg", locationId: "berat", locationLabel: "Berat", caption: "March 2026" },
    ],
  },
  Argentina: {
    folder: "argentina",
    photos: [
      { file: "IMG_1504.jpg", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1506.jpg", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1579.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1602.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1652.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024", cover: true },
      { file: "IMG_1684.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1691.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1694.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1695.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1696.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1707.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1708.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_7586.jpeg", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_7806.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_9701.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
    ],
  },
  Austria: { folder: "austria", photos: [] },
  "Bosnia and Herzegovina": { folder: "bosnia-and-herzegovina", photos: [] },
  Cambodia: {
    folder: "cambodia",
    photos: [
      { file: "IMG_0355.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_0403.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_0454.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_0469.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_0470.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_0580.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024", cover: true },
      { file: "IMG_0648.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_0676.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_7623.JPG", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_8587.jpg", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_8598.jpg", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_8825.jpg", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_8828.jpg", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_8835.jpg", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_8837.jpg", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_8864.jpg", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },
      { file: "IMG_8885.jpg", locationId: "siem-reap", locationLabel: "Siem Reap", caption: "May 2024" },

      { file: "IMG_0740.JPG", locationId: "phnom-penh", locationLabel: "Phnom Penh", caption: "May 2024" },
      { file: "IMG_0750.JPG", locationId: "phnom-penh", locationLabel: "Phnom Penh", caption: "May 2024" },
      { file: "IMG_0783.JPG", locationId: "phnom-penh", locationLabel: "Phnom Penh", caption: "May 2024" },
      { file: "IMG_5091.jpg", locationId: "phnom-penh", locationLabel: "Phnom Penh", caption: "May 2024" },
      { file: "IMG_8921.jpg", locationId: "phnom-penh", locationLabel: "Phnom Penh", caption: "May 2024" },
    ],
  },
  Chile: {
    folder: "chile",
    photos: [
      { file: "IMG_1605.jpg", locationId: "valparaiso", caption: "January 2025" },
      { file: "IMG_1758.JPG", locationId: "valparaiso", caption: "January 2025" },
      { file: "IMG_1761.JPG", locationId: "valparaiso", caption: "January 2025" },
      { file: "IMG_1792.JPG", locationId: "valparaiso", caption: "January 2025" },
      { file: "IMG_1608.jpg", locationId: "olmue", caption: "January 2025" },
      { file: "IMG_1723.JPG", locationId: "olmue", caption: "January 2025" },
      { file: "IMG_1725.JPG", locationId: "olmue", caption: "January 2025" },
      { file: "IMG_1578.jpg", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
      { file: "IMG_1626.jpg", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
      { file: "IMG_1628.jpg", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025", cover: true },
      { file: "IMG_1730.JPG", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
      { file: "IMG_1733.JPG", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
      { file: "IMG_1749.JPG", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
    ],
  },
  Croatia: { folder: "croatia", photos: [] },
  France: {
    folder: "france",
    photos: [
      { file: "RemoteMediaFile_6554090_0_2022_07_03_19_49_42.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "RemoteMediaFile_6554096_0_2022_07_03_21_52_04.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022", cover: true },
      { file: "RemoteMediaFile_6554105_0_2022_07_03_21_58_36.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2292.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2336.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2344.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2345.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2436.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2442.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2521.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2575.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_4038.JPG", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "RemoteMediaFile_6554083_0_2022_07_03_19_44_58.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "RemoteMediaFile_6554087_0_2022_07_03_19_47_44.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "RemoteMediaFile_6554089_0_2022_07_03_19_49_32.jpg", locationId: "paris", locationLabel: "Paris", caption: "July 2022" },
      { file: "IMG_2627.jpg", locationId: "versailles", locationLabel: "Versailles", caption: "July 2022" },
      { file: "IMG_4160.jpg", locationId: "versailles", locationLabel: "Versailles", caption: "July 2022" },
      { file: "IMG_4163.jpg", locationId: "versailles", locationLabel: "Versailles", caption: "July 2022" },
    ],
  },
  Germany: { folder: "germany", photos: [] },
  Hungary: { folder: "hungary", photos: [] },
  Ireland: { folder: "ireland", photos: [] },
  Italy: { folder: "italy", photos: [] },
  Monaco: { folder: "monaco", photos: [] },
  Montenegro: { folder: "montenegro", photos: [] },
  Morocco: { folder: "morocco", photos: [] },
  Peru: {
    folder: "peru",
    photos: [
      { file: "IMG_1998.JPG", caption: "May 2025", locationId: "cusco" },
      { file: "IMG_3394.jpg", caption: "May 2025", locationId: "cusco" },
      { file: "IMG_3390.jpg", caption: "May 2025", locationId: "cusco" },
      { file: "IMG_3423.jpg", caption: "Salkantay Trek May 2025", cover: true },
      { file: "IMG_3441.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_3447.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_3474.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_3521.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_0026.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_0060.JPG", caption: "Salkantay Trek May 2025" },
      { file: "IMG_2453.JPG", caption: "Salkantay Trek May 2025" },
      { file: "IMG_2216.JPG", caption: "Machu Picchu May 2025" },
      { file: "IMG_2596.JPG", caption: "Machu Picchu May 2025" },
      { file: "IMG_3547.jpg", caption: "Machu Picchu May 2025" },
      { file: "machu-picchu.jpg", caption: "Machu Picchu May 2025" },
      { file: "IMG_3663.jpg", caption: "May 2025", locationId: "arequipa" },
      { file: "IMG_3669.jpg", caption: "May 2025", locationId: "arequipa" },
      { file: "IMG_3673.jpg", caption: "May 2025", locationId: "arequipa" },
      { file: "IMG_3690.jpg", caption: "May 2025", locationId: "huacachina" },
      { file: "IMG_3711.jpg", caption: "May 2025", locationId: "huacachina" },
      { file: "IMG_3714.jpg", caption: "May 2025", locationId: "huacachina" },
      { file: "IMG_3717.jpg", caption: "May 2025", locationId: "huacachina" },
      { file: "IMG_3752.jpg", caption: "May 2025", locationId: "lima" },
      { file: "IMG_3754.jpg", caption: "May 2025", locationId: "lima" },
    ],
  },
  Portugal: { folder: "portugal", photos: [] },
  Slovenia: { folder: "slovenia", photos: [] },
  Spain: { folder: "spain", photos: [] },
  Switzerland: { folder: "switzerland", photos: [] },
  Thailand: {
    folder: "thailand",
    photos: [
      { file: "IMG_0007.JPG", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_0014.JPG", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024", cover: true },
      { file: "IMG_0021.JPG", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_0074.jpg", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_0177.JPG", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_0260.JPG", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_0290.JPG", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_7383.JPG", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_8743.jpg", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_8773.jpg", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_8789.jpg", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_8790.jpg", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_8791.jpg", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
      { file: "IMG_8795.jpg", locationId: "bangkok", locationLabel: "Bangkok", caption: "May 2024" },
    ],
  },
  "United Kingdom": {
    folder: "united-kingdom",
    photos: [
      { file: "1969b5ce-a016-4b0b-b593-3d5a519a0f94.JPG", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "IMG_1601.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "IMG_1605.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "IMG_1648.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554018_0_2022_04_12_11_32_34.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554023_0_2022_04_13_09_54_28.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554027_0_2022_04_13_10_45_08.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554029_0_2022_04_13_10_47_46.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554030_0_2022_04_13_10_48_22.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554032_0_2022_04_13_10_49_20.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554035_0_2022_04_13_12_10_44.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554036_0_2022_04_13_12_10_58.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554039_0_2022_04_13_12_12_00.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554040_0_2022_04_13_12_12_36.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },
      { file: "RemoteMediaFile_6554041_0_2022_04_13_12_13_14.jpg", locationId: "london", locationLabel: "London", caption: "April 2022" },

      { file: "RemoteMediaFile_6554048_0_2022_04_15_12_46_26.jpg", locationId: "cambridge", locationLabel: "Cambridge", caption: "April 2022" },
      { file: "RemoteMediaFile_6554055_0_2022_04_15_14_07_46.jpg", locationId: "cambridge", locationLabel: "Cambridge", caption: "April 2022" },
      { file: "RemoteMediaFile_6554057_0_2022_04_15_14_08_38.jpg", locationId: "cambridge", locationLabel: "Cambridge", caption: "April 2022" },
      { file: "RemoteMediaFile_6554058_0_2022_04_15_14_09_00.jpg", locationId: "cambridge", locationLabel: "Cambridge", caption: "April 2022" },
      { file: "RemoteMediaFile_6554060_0_2022_04_15_14_10_02.jpg", locationId: "cambridge", locationLabel: "Cambridge", caption: "April 2022" },
      { file: "RemoteMediaFile_6554064_0_2022_04_15_14_15_16.jpg", locationId: "cambridge", locationLabel: "Cambridge", caption: "April 2022" },
      { file: "RemoteMediaFile_6554067_0_2022_04_15_14_17_04.jpg", locationId: "cambridge", locationLabel: "Cambridge", caption: "April 2022" },

      { file: "IMG_1713.jpg", locationId: "manchester", locationLabel: "Manchester", caption: "April 2022" },
      { file: "IMG_1720.jpg", locationId: "manchester", locationLabel: "Manchester", caption: "April 2022" },
      { file: "IMG_3610.jpg", locationId: "manchester", locationLabel: "Manchester", caption: "April 2022" },
      { file: "RemoteMediaFile_6554075_0_2022_04_16_10_25_32.jpg", locationId: "manchester", locationLabel: "Manchester", caption: "April 2022" },
      { file: "RemoteMediaFile_6554077_0_2022_04_16_10_27_08.jpg", locationId: "manchester", locationLabel: "Manchester", caption: "April 2022" },

      { file: "RemoteMediaFile_6554146_0_2022_07_10_21_51_56.jpg", locationId: "edinburgh", locationLabel: "Edinburgh", caption: "July 2022" },
      { file: "RemoteMediaFile_6554147_0_2022_07_10_21_53_20.jpg", locationId: "edinburgh", locationLabel: "Edinburgh", caption: "July 2022" },
      { file: "RemoteMediaFile_6554148_0_2022_07_10_21_54_06.jpg", locationId: "edinburgh", locationLabel: "Edinburgh", caption: "July 2022", cover: true },
      { file: "RemoteMediaFile_6554149_0_2022_07_10_21_54_22.jpg", locationId: "edinburgh", locationLabel: "Edinburgh", caption: "July 2022" },
      { file: "RemoteMediaFile_6554150_0_2022_07_10_21_54_32.jpg", locationId: "edinburgh", locationLabel: "Edinburgh", caption: "July 2022" },
      { file: "RemoteMediaFile_6554151_0_2022_07_10_21_55_10.jpg", locationId: "edinburgh", locationLabel: "Edinburgh", caption: "July 2022" },
      { file: "RemoteMediaFile_6554152_0_2022_07_10_21_56_16.jpg", locationId: "edinburgh", locationLabel: "Edinburgh", caption: "July 2022" },
      { file: "RemoteMediaFile_6554153_0_2022_07_12_17_36_16.jpg", locationId: "edinburgh", locationLabel: "Edinburgh", caption: "July 2022" },
    ],
  },
  "United States": {
    folder: "united-states",
    photos: [
      { file: "IMG_3311.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_3316.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_3324.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_3331.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_3338.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_8437.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "April 2024" },
      { file: "IMG_1306.jpeg", locationId: "nashville", locationLabel: "Nashville", caption: "April 2024" },

      { file: "IMG_4546.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "August 2025" },
      { file: "IMG_4729.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "August 2025" },
      { file: "IMG_1820.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "August 2025" },
      { file: "IMG_4754.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "August 2025" },
      { file: "IMG_4742.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "August 2025" },
      { file: "IMG_1655.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "August 2025" },
      { file: "IMG_4777.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "August 2025" },
      { file: "IMG_3216.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "July 2025" },
      { file: "IMG_4462.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "July 2025" },
      { file: "IMG_4476.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "July 2025" },
      { file: "IMG_4522.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "July 2025" },
      { file: "IMG_4555.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "July 2025" },
      { file: "IMG_4580.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "July 2025" },
      { file: "IMG_4074.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "June 2025" },
      { file: "IMG_3201.JPG", locationId: "louisville", locationLabel: "Louisville", caption: "May 2025" },
      { file: "IMG_3893.JPG", locationId: "louisville", locationLabel: "Louisville", caption: "May 2025" },
      { file: "IMG_9036.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "May 2025" },
      { file: "IMG_1982.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "April 2025" },
      { file: "IMG_2853.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "April 2025" },
      { file: "IMG_3114.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "April 2025" },
      { file: "IMG_4275.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "April 2025" },
      { file: "IMG_8648.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "April 2025" },
      { file: "SAM_1494.jpeg", locationId: "louisville", locationLabel: "Louisville", caption: "April 2025" },
      { file: "IMG_3146.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "April 2025" },
      { file: "IMG_2050.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "March 2025" },
      { file: "IMG_2069.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "March 2025" },
      { file: "IMG_2076.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "March 2025" },
      { file: "IMG_1746.jpg", locationId: "louisville", locationLabel: "Louisville", caption: "January 2025" },

      { file: "IMG_0586.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0616.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0609.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0624.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0641.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0601.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0646.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0660.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0708.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0722.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0735.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0737.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0765.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0787.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "72083291276__5CCED1D6-43AD-4D60-8102-4772A4EB8CAC.jpg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "November 2023" },
      { file: "IMG_0933.jpg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "November 2023" },
      { file: "IMG_2947.jpeg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "November 2023" },
      { file: "IMG_3170.jpg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "November 2023" },
      { file: "IMG_3184.jpg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "November 2023" },

      { file: "IMG_5651.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2025" },
      { file: "IMG_5654.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2025" },
      { file: "IMG_5700.JPG", locationId: "chicago", locationLabel: "Chicago", caption: "November 2025" },
      { file: "IMG_5710.JPG", locationId: "chicago", locationLabel: "Chicago", caption: "November 2025" },
      { file: "IMG_2884.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "April 2025" },
      { file: "IMG_7221.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2023" },
      { file: "IMG_7222.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2023" },
      { file: "72090121867__9B50DBA4-6CC4-4EEA-81CB-33D64F50BE26.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2023" },
      { file: "IMG_6942.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "October 2023" },
      { file: "IMG_2110.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "October 2023" },
      { file: "IMG_6945.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "October 2023" },

      { file: "dji_fly_20231103_132912_972_1699036619763_photo_optimized.jpg", locationId: "indiana-dunes", locationLabel: "Indiana Dunes", caption: "November 2023" },
      { file: "dji_fly_20231103_133024_974_1699036618500_photo_optimized.jpg", locationId: "indiana-dunes", locationLabel: "Indiana Dunes", caption: "November 2023" },
      { file: "dji_fly_20231103_133240_982_1699036637344_photo_optimized.jpg", locationId: "indiana-dunes", locationLabel: "Indiana Dunes", caption: "November 2023" },
      { file: "dji_fly_20231103_133450_994_1699036570414_timed.jpg", locationId: "indiana-dunes", locationLabel: "Indiana Dunes", caption: "November 2023" },
      { file: "IMG_7154.jpg", locationId: "indiana-dunes", locationLabel: "Indiana Dunes", caption: "November 2023" },

      { file: "dji_fly_20230404_133602_602_1680630108296_photo_optimized.jpg", locationId: "new-paltz", locationLabel: "New Paltz", caption: "April 2023" },
      { file: "dji_fly_20230404_133726_603_1680630112172_photo_optimized.jpg", locationId: "new-paltz", locationLabel: "New Paltz", caption: "April 2023" },
      { file: "dji_fly_20230404_133750_604_1680630119419_photo_optimized.jpg", locationId: "new-paltz", locationLabel: "New Paltz", caption: "April 2023" },
      { file: "IMG_4576.jpeg", locationId: "new-paltz", locationLabel: "New Paltz", caption: "April 2023" },
      { file: "IMG_2794.jpeg", locationId: "new-paltz", locationLabel: "New Paltz", caption: "April 2023" },
      { file: "IMG_2795.jpeg", locationId: "new-paltz", locationLabel: "New Paltz", caption: "April 2023" },
      { file: "IMG_4579.jpeg", locationId: "new-paltz", locationLabel: "New Paltz", caption: "April 2023" },

      { file: "RemoteMediaFile_6553944_0_2021_11_27_06_56_56.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_0239.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_0242.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_8285.JPG", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_8286.JPG", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_8287.JPG", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_8288.JPG", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_0234.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_8292.JPG", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_8358.JPG", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "IMG_8366.JPG", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "RemoteMediaFile_6553934_0_2021_11_27_06_51_00.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "RemoteMediaFile_6553939_0_2021_11_27_06_52_54.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "RemoteMediaFile_6553951_0_2021_11_27_07_08_08.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "RemoteMediaFile_6553971_0_2021_11_27_11_38_50.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "RemoteMediaFile_6553972_0_2021_11_27_11_40_22.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },
      { file: "RemoteMediaFile_6553977_0_2021_11_27_11_43_10.jpg", locationId: "philadelphia", locationLabel: "Philadelphia", caption: "November 2021" },

      { file: "RemoteMediaFile_6553986_0_2022_01_31_07_04_00.jpg", locationId: "blacksburg", locationLabel: "Blacksburg", caption: "January 2022" },
      { file: "RemoteMediaFile_6554004_0_2022_01_31_07_13_36.jpg", locationId: "blacksburg", locationLabel: "Blacksburg", caption: "January 2022" },
      { file: "RemoteMediaFile_6554006_0_2022_01_31_07_14_58.jpg", locationId: "blacksburg", locationLabel: "Blacksburg", caption: "January 2022" },
      { file: "RemoteMediaFile_6554008_0_2022_01_31_07_15_58.jpg", locationId: "blacksburg", locationLabel: "Blacksburg", caption: "January 2022" },
      { file: "RemoteMediaFile_6554011_0_2022_01_31_07_17_58.jpg", locationId: "blacksburg", locationLabel: "Blacksburg", caption: "January 2022" },

      { file: "dji_fly_20220825_111954_556_1661441017229_photo_optimized.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "dji_fly_20220825_164136_564_1661460845663_timed_optimized.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "dji_fly_20220825_164414_573_1661460842843_photo_optimized.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "dji_fly_20220825_194232_590_1661471635140_photo_optimized.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "dji_fly_20220825_194722_598_1661471550944_photo_optimized.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_2361.JPG", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_2373.JPG", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_2392.JPG", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_3063.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_3080.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_3104.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_3105.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_3109.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_3111.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_3113.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },
      { file: "IMG_3116.jpg", locationId: "white-mountains", locationLabel: "White Mountains", caption: "August 2022" },

      { file: "IMG_0024.JPG", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0859.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0862.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0864.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0867.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0870.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0880.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0913.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0915.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0921.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0924.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0928.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },

      { file: "IMG_1915.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1923.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1319.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1411.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1246.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1932.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_2973.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_3024.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_3039.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025", cover: true },
      { file: "IMG_3059.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_8900.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1489.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_8905.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_8950.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_2199.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "July 2018" },
      { file: "IMG_2518.jpeg", locationId: "seattle", locationLabel: "Seattle", caption: "July 2018" },
    ],
  },
  Uruguay: {
    folder: "uruguay",
    photos: [
      { file: "IMG_1675.JPG", locationId: "colonia-del-sacramento", locationLabel: "Colonia del Sacramento", caption: "December 2024", cover: true },
      { file: "IMG_1684(1).JPG", locationId: "colonia-del-sacramento", locationLabel: "Colonia del Sacramento", caption: "December 2024" },
      { file: "IMG_7752.JPG", locationId: "colonia-del-sacramento", locationLabel: "Colonia del Sacramento", caption: "December 2024" },
      { file: "IMG_1694(1).JPG", locationId: "montevideo", locationLabel: "Montevideo", caption: "December 2024" },
    ],
  },
  Vietnam: {
    folder: "vietnam",
    photos: [
      { file: "IMG_0859.JPG", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },
      { file: "IMG_0866.JPG", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024", cover: true },
      { file: "IMG_0877.JPG", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },
      { file: "IMG_0900.JPG", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },
      { file: "IMG_1214.JPG", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },
      { file: "IMG_5369.JPG", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },
      { file: "IMG_7847.JPG", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },
      { file: "IMG_8930.jpg", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },
      { file: "IMG_8935.jpg", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },
      { file: "IMG_8977.jpg", locationId: "ho-chi-minh-city", locationLabel: "Ho Chi Minh City", caption: "May 2024" },

      { file: "IMG_0976.JPG", locationId: "hoi-an", locationLabel: "Hoi An", caption: "May 2024" },
      { file: "IMG_0978.JPG", locationId: "hoi-an", locationLabel: "Hoi An", caption: "May 2024" },
      { file: "IMG_8990.jpg", locationId: "hoi-an", locationLabel: "Hoi An", caption: "May 2024" },
      { file: "IMG_8992.jpg", locationId: "hoi-an", locationLabel: "Hoi An", caption: "May 2024" },

      { file: "IMG_1105.JPG", locationId: "ninh-binh", locationLabel: "Ninh Binh", caption: "May 2024" },
      { file: "IMG_5512.JPG", locationId: "ninh-binh", locationLabel: "Ninh Binh", caption: "May 2024" },
      { file: "IMG_5515.JPG", locationId: "ninh-binh", locationLabel: "Ninh Binh", caption: "May 2024" },
      { file: "IMG_8003.jpg", locationId: "ninh-binh", locationLabel: "Ninh Binh", caption: "May 2024" },
      { file: "IMG_9015.jpg", locationId: "ninh-binh", locationLabel: "Ninh Binh", caption: "May 2024" },
      { file: "IMG_9016.jpg", locationId: "ninh-binh", locationLabel: "Ninh Binh", caption: "May 2024" },

      { file: "IMG_1120.JPG", locationId: "hanoi", locationLabel: "Hanoi", caption: "May 2024" },
      { file: "IMG_1122.JPG", locationId: "hanoi", locationLabel: "Hanoi", caption: "May 2024" },
      { file: "IMG_5561.JPG", locationId: "hanoi", locationLabel: "Hanoi", caption: "May 2024" },
      { file: "IMG_5573.JPG", locationId: "hanoi", locationLabel: "Hanoi", caption: "May 2024" },
      { file: "IMG_5585.JPG", locationId: "hanoi", locationLabel: "Hanoi", caption: "May 2024" },
      { file: "IMG_5685.JPG", locationId: "hanoi", locationLabel: "Hanoi", caption: "May 2024" },
      { file: "IMG_9095.JPG", locationId: "hanoi", locationLabel: "Hanoi", caption: "May 2024" },
      { file: "IMG_9097.jpg", locationId: "hanoi", locationLabel: "Hanoi", caption: "June 2024" },
      { file: "FD83450F-F1C0-4E54-8D49-236FDFD2BE2B.jpg", locationId: "hanoi", locationLabel: "Hanoi", caption: "June 2024" },
      { file: "IMG_9195.jpg", locationId: "hanoi", locationLabel: "Hanoi", caption: "June 2024" },

      { file: "IMG_1207.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_1209.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_1220.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_1223.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_1247.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_1268.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_1295.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_5784.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_5791.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_8162.JPG", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_9108.jpg", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_9141.jpg", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
      { file: "IMG_9165.jpg", locationId: "ha-long-bay", locationLabel: "Ha Long Bay", caption: "June 2024" },
    ],
  },
};
