export type CountryPhoto = {
  file: string;
  caption?: string;
  locationId?: string;
  locationLabel?: string;
  date?: string;
  cover?: boolean;
};

export type CountryPhotoAlbum = {
  folder: string;
  photos: CountryPhoto[];
};

// Example:
// Spain: {
//   folder: "spain",
//   photos: [
//     {
//       file: "atletico-game.jpg",
//       caption: "Atletico game",
//       locationId: "madrid",
//       locationLabel: "Madrid",
//       cover: true,
//     },
//   ],
// },
export const COUNTRY_PHOTO_ALBUMS: Record<string, CountryPhotoAlbum> = {
  Albania: { folder: "albania", photos: [] },
  Argentina: {
    folder: "argentina",
    photos: [
      { file: "IMG_1504.jpg", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1506.jpg", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1579.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1602.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1652.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024", cover: true },
      { file: "IMG_1684.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1691.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1694.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1695.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1696.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1707.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_1708.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_7586.jpeg", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_7806.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
      { file: "IMG_9701.JPG", locationId: "buenos-aires", locationLabel: "Buenos Aires", caption: "December 2024" },
    ],
  },
  Austria: { folder: "austria", photos: [] },
  "Bosnia and Herzegovina": { folder: "bosnia-and-herzegovina", photos: [] },
  Cambodia: { folder: "cambodia", photos: [] },
  Chile: {
    folder: "chile",
    photos: [
      { file: "IMG_1605.jpg", locationId: "valparaiso", caption: "January 2025" },
      { file: "IMG_1758.JPG", locationId: "valparaiso", caption: "January 2025" },
      { file: "IMG_1761.JPG", locationId: "valparaiso", caption: "January 2025" },
      { file: "IMG_1792.JPG", locationId: "valparaiso", caption: "January 2025" },
      { file: "IMG_1608.jpg", locationId: "olmue", caption: "January 2025" },
      { file: "IMG_1723.JPG", locationId: "olmue", caption: "January 2025" },
      { file: "IMG_1725.JPG", locationId: "olmue", caption: "January 2025" },
      { file: "IMG_1578.jpg", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
      { file: "IMG_1626.jpg", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
      { file: "IMG_1628.jpg", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025", cover: true },
      { file: "IMG_1730.JPG", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
      { file: "IMG_1733.JPG", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
      { file: "IMG_1749.JPG", locationId: "santiago", locationLabel: "Santiago", caption: "January 2025" },
    ],
  },
  Croatia: { folder: "croatia", photos: [] },
  France: { folder: "france", photos: [] },
  Germany: { folder: "germany", photos: [] },
  Hungary: { folder: "hungary", photos: [] },
  Ireland: { folder: "ireland", photos: [] },
  Italy: { folder: "italy", photos: [] },
  Monaco: { folder: "monaco", photos: [] },
  Montenegro: { folder: "montenegro", photos: [] },
  Morocco: { folder: "morocco", photos: [] },
  Peru: {
    folder: "peru",
    photos: [
      { file: "IMG_1998.JPG", caption: "May 2025", locationId: "cusco" },
      { file: "IMG_3394.jpg", caption: "May 2025", locationId: "cusco" },
      { file: "IMG_3390.jpg", caption: "May 2025", locationId: "cusco" },
      { file: "IMG_3423.jpg", caption: "Salkantay Trek May 2025", cover: true },
      { file: "IMG_3441.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_3447.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_3474.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_3521.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_0026.jpg", caption: "Salkantay Trek May 2025" },
      { file: "IMG_0060.JPG", caption: "Salkantay Trek May 2025" },
      { file: "IMG_2453.JPG", caption: "Salkantay Trek May 2025" },
      { file: "IMG_2216.JPG", caption: "Machu Picchu May 2025" },
      { file: "IMG_2596.JPG", caption: "Machu Picchu May 2025" },
      { file: "IMG_3547.jpg", caption: "Machu Picchu May 2025" },
      { file: "machu-picchu.jpg", caption: "Machu Picchu May 2025" },
      { file: "IMG_3663.jpg", caption: "May 2025", locationId: "arequipa" },
      { file: "IMG_3669.jpg", caption: "May 2025", locationId: "arequipa" },
      { file: "IMG_3673.jpg", caption: "May 2025", locationId: "arequipa" },
      { file: "IMG_3690.jpg", caption: "May 2025", locationId: "huacachina" },
      { file: "IMG_3711.jpg", caption: "May 2025", locationId: "huacachina" },
      { file: "IMG_3714.jpg", caption: "May 2025", locationId: "huacachina" },
      { file: "IMG_3717.jpg", caption: "May 2025", locationId: "huacachina" },
      { file: "IMG_3752.jpg", caption: "May 2025", locationId: "lima" },
      { file: "IMG_3754.jpg", caption: "May 2025", locationId: "lima" },
    ],
  },
  Portugal: { folder: "portugal", photos: [] },
  Slovenia: { folder: "slovenia", photos: [] },
  Spain: { folder: "spain", photos: [] },
  Switzerland: { folder: "switzerland", photos: [] },
  Thailand: { folder: "thailand", photos: [] },
  "United Kingdom": { folder: "united-kingdom", photos: [] },
  "United States": {
    folder: "united-states",
    photos: [
      { file: "IMG_3311.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_3316.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_3324.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_3331.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_3338.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "May 2025" },
      { file: "IMG_8437.jpg", locationId: "nashville", locationLabel: "Nashville", caption: "April 2024" },
      { file: "IMG_1306.jpeg", locationId: "nashville", locationLabel: "Nashville", caption: "April 2024" },

      { file: "IMG_0586.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0616.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0609.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0624.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0641.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0601.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0646.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0660.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0708.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0722.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0735.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0737.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0765.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "IMG_0787.JPG", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2024" },
      { file: "72083291276__5CCED1D6-43AD-4D60-8102-4772A4EB8CAC.jpg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2023" },
      { file: "IMG_0933.jpg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2023" },
      { file: "IMG_2947.jpeg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2023" },
      { file: "IMG_3170.jpg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2023" },
      { file: "IMG_3184.jpg", locationId: "ann-arbor", locationLabel: "Ann Arbor", caption: "October 2023" },

      { file: "IMG_5651.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2025" },
      { file: "IMG_5654.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2025" },
      { file: "IMG_5700.JPG", locationId: "chicago", locationLabel: "Chicago", caption: "November 2025" },
      { file: "IMG_5710.JPG", locationId: "chicago", locationLabel: "Chicago", caption: "November 2025" },
      { file: "IMG_2884.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "April 2025" },
      { file: "IMG_7221.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2023" },
      { file: "IMG_7222.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2023" },
      { file: "72090121867__9B50DBA4-6CC4-4EEA-81CB-33D64F50BE26.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "November 2023" },
      { file: "IMG_6942.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "October 2023" },
      { file: "IMG_2110.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "October 2023" },
      { file: "IMG_6945.jpg", locationId: "chicago", locationLabel: "Chicago", caption: "October 2023" },

      { file: "IMG_0024.JPG", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0859.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0862.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0864.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0867.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0870.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0880.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0913.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0915.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0921.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0924.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },
      { file: "IMG_0928.jpg", locationId: "san-juan", locationLabel: "San Juan", caption: "October 2024" },

      { file: "IMG_1915.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1923.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1319.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1411.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1246.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1932.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_2973.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_3024.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_3039.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025", cover: true },
      { file: "IMG_3059.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_8900.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_1489.jpg", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_8905.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_8950.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "April 2025" },
      { file: "IMG_2199.JPG", locationId: "seattle", locationLabel: "Seattle", caption: "July 2018" },
      { file: "IMG_2518.jpeg", locationId: "seattle", locationLabel: "Seattle", caption: "July 2018" },
    ],
  },
  Uruguay: {
    folder: "uruguay",
    photos: [
      { file: "IMG_1675.JPG", locationId: "colonia-del-sacramento", locationLabel: "Colonia del Sacramento", caption: "December 2024", cover: true },
      { file: "IMG_1684(1).JPG", locationId: "colonia-del-sacramento", locationLabel: "Colonia del Sacramento", caption: "December 2024" },
      { file: "IMG_7752.JPG", locationId: "colonia-del-sacramento", locationLabel: "Colonia del Sacramento", caption: "December 2024" },
      { file: "IMG_1694(1).JPG", locationId: "montevideo", locationLabel: "Montevideo", caption: "December 2024" },
    ],
  },
  Vietnam: { folder: "vietnam", photos: [] },
};
