export type TravelPhoto = {
  src: string;
  caption: string;
  date?: string;
};

export type Location = {
  id: string;
  name: string;
  country: string;
  region: string;
  coords: [number, number];
  coverPhoto?: string;
  coverCaption?: string;
  photos: TravelPhoto[];
};

export type TransportMode = "plane" | "train" | "road" | "boat";

export type RouteSegment = {
  id: string;
  origin: string;
  destination: string;
  mode: TransportMode;
  month?: string;
};

export const MODE_STYLES: Record<TransportMode, { label: string; color: string }> = {
  plane: { label: "Plane", color: "#6EA8FE" },
  train: { label: "Train", color: "#4DD4AC" },
  road: { label: "Road", color: "#F59E6B" },
  boat: { label: "Boat", color: "#ba4ddc" },
};

export const LOCATIONS: Location[] = [
  {
    id: "washington-dc",
    name: "Washington, DC",
    country: "United States",
    region: "North America",
    coords: [-77.0369, 38.9072],
    photos: [],
  },
  {
    id: "louisville",
    name: "Louisville",
    country: "United States",
    region: "North America",
    coords: [-85.7585, 38.2527],
    photos: [],
  },
  {
    id: "chicago",
    name: "Chicago",
    country: "United States",
    region: "North America",
    coords: [-87.6298, 41.8781],
    photos: [],
  },
  {
    id: "west-lafayette",
    name: "West Lafayette",
    country: "United States",
    region: "North America",
    coords: [-86.9081, 40.4259],
    photos: [],
  },
  {
    id: "indianapolis",
    name: "Indianapolis",
    country: "United States",
    region: "North America",
    coords: [-86.1581, 39.7684],
    photos: [],
  },
  {
    id: "seattle",
    name: "Seattle",
    country: "United States",
    region: "North America",
    coords: [-122.3321, 47.6062],
    photos: [],
  },
  {
    id: "philadelphia",
    name: "Philadelphia",
    country: "United States",
    region: "North America",
    coords: [-75.1652, 39.9526],
    photos: [],
  },
  {
    id: "nashville",
    name: "Nashville",
    country: "United States",
    region: "North America",
    coords: [-86.7816, 36.1627],
    photos: [],
  },
  {
    id: "san-juan",
    name: "San Juan",
    country: "United States",
    region: "North America",
    coords: [-66.1057, 18.4655],
    photos: [],
  },
  {
    id: "tampa",
    name: "Tampa",
    country: "United States",
    region: "North America",
    coords: [-82.4572, 27.9506],
    photos: [],
  },
  {
    id: "st. petersburg",
    name: "St. Petersburg",
    country: "United States",
    region: "North America",
    coords: [-82.6403, 27.7676],
    photos: [],
  },
  {
    id: "boston",
    name: "Boston",
    country: "United States",
    region: "North America",
    coords: [-71.0589, 42.3601],
    photos: [],
  },
  {
    id: "castine",
    name: "Castine",
    country: "United States",
    region: "North America",
    coords: [-68.7998, 44.3879],
    photos: [],
  },
  {
    id: "gainesville",
    name: "Gainesville",
    country: "United States",
    region: "North America",
    coords: [-82.3248, 29.6516],
    photos: [],
  },
  {
    id: "corolla",
    name: "Corolla",
    country: "United States",
    region: "North America",
    coords: [-75.8308, 36.3807],
    photos: [],
  },
  {
    id: "hanover-nh",
    name: "Hanover, NH",
    country: "United States",
    region: "North America",
    coords: [-72.2896, 43.7022],
    photos: [],
  },
  {
    id: "deep-creek",
    name: "Deep Creek",
    country: "United States",
    region: "North America",
    coords: [-79.3817, 39.4926],
    photos: [],
  },
  {
    id: "north-conway",
    name: "North Conway",
    country: "United States",
    region: "North America",
    coords: [-71.1284, 44.0537],
    photos: [],
  },
  {
    id: "madrid",
    name: "Madrid",
    country: "Spain",
    region: "Europe",
    coords: [-3.7038, 40.4168],
    photos: [],
  },
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    region: "Europe",
    coords: [2.1734, 41.3851],
    photos: [],
  },
  {
    id: "bilbao",
    name: "Bilbao",
    country: "Spain",
    region: "Europe",
    coords: [-2.935, 43.263],
    photos: [],
  },
  {
    id: "salamanca",
    name: "Salamanca",
    country: "Spain",
    region: "Europe",
    coords: [-5.6635, 40.9701],
    photos: [],
  },
  {
    id: "segovia",
    name: "Segovia",
    country: "Spain",
    region: "Europe",
    coords: [-4.1088, 40.9429],
    photos: [],
  },
  {
    id: "toledo",
    name: "Toledo",
    country: "Spain",
    region: "Europe",
    coords: [-4.0273, 39.8628],
    photos: [],
  },
  {
    id: "marseille",
    name: "Marseille",
    country: "France",
    region: "Europe",
    coords: [5.3698, 43.2965],
    photos: [],
  },
  {
    id: "antibes",
    name: "Antibes",
    country: "France",
    region: "Europe",
    coords: [7.1251, 43.5804],
    photos: [],
  },
  {
    id: "bolzano",
    name: "Bolzano",
    country: "Italy",
    region: "Europe",
    coords: [11.3548, 46.4983],
    photos: [],
  },
  {
    id: "venice",
    name: "Venice",
    country: "Italy",
    region: "Europe",
    coords: [12.3155, 45.4408],
    photos: [],
  },
  {
    id: "ljubljana",
    name: "Ljubljana",
    country: "Slovenia",
    region: "Europe",
    coords: [14.5058, 46.0569],
    photos: [],
  },
  {
    id: "lake-bled",
    name: "Lake Bled",
    country: "Slovenia",
    region: "Europe",
    coords: [14.0946, 46.3632],
    photos: [],
  },
  {
    id: "zagreb",
    name: "Zagreb",
    country: "Croatia",
    region: "Europe",
    coords: [15.9819, 45.815],
    photos: [],
  },
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    region: "Europe",
    coords: [-0.1276, 51.5072],
    photos: [],
  },
  {
    id: "cambridge",
    name: "Cambridge",
    country: "United Kingdom",
    region: "Europe",
    coords: [0.1218, 52.2053],
    photos: [],
  },
  {
    id: "edinburgh",
    name: "Edinburgh",
    country: "United Kingdom",
    region: "Europe",
    coords: [-3.1883, 55.9533],
    photos: [],
  },
  {
    id: "st-andrews",
    name: "St. Andrews",
    country: "United Kingdom",
    region: "Europe",
    coords: [-2.7967, 56.3398],
    photos: [],
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    region: "Europe",
    coords: [2.3522, 48.8566],
    photos: [],
  },
  {
    id: "monaco",
    name: "Monaco",
    country: "Monaco",
    region: "Europe",
    coords: [7.4246, 43.7384],
    photos: [],
  },
  {
    id: "versailles",
    name: "Versailles",
    country: "France",
    region: "Europe",
    coords: [2.1301, 48.8014],
    photos: [],
  },
  {
    id: "budapest",
    name: "Budapest",
    country: "Hungary",
    region: "Europe",
    coords: [19.0402, 47.4979],
    photos: [],
  },
  {
    id: "zurich",
    name: "Zurich",
    country: "Switzerland",
    region: "Europe",
    coords: [8.5417, 47.3769],
    photos: [],
  },
  {
    id: "st-anton",
    name: "St. Anton am Arlberg",
    country: "Austria",
    region: "Europe",
    coords: [10.2647, 47.1296],
    photos: [],
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    region: "Europe",
    coords: [-9.1393, 38.7223],
    photos: [],
  },
  {
    id: "sintra",
    name: "Sintra",
    country: "Portugal",
    region: "Europe",
    coords: [-9.3817, 38.8029],
    photos: [],
  },
  {
    id: "tirana",
    name: "Tirana",
    country: "Albania",
    region: "Europe",
    coords: [19.8187, 41.3275],
    photos: [],
  },
  {
    id: "berat",
    name: "Berat",
    country: "Albania",
    region: "Europe",
    coords: [19.9522, 40.7058],
    photos: [],
  },
  {
    id: "dublin",
    name: "Dublin",
    country: "Ireland",
    region: "Europe",
    coords: [-6.2603, 53.3498],
    photos: [],
  },
  {
    id: "dingle",
    name: "Dingle",
    country: "Ireland",
    region: "Europe",
    coords: [-10.2717, 52.1409],
    photos: [],
  },
  {
    id: "split",
    name: "Split",
    country: "Croatia",
    region: "Europe",
    coords: [16.4402, 43.5081],
    photos: [],
  },
  {
    id: "mostar",
    name: "Mostar",
    country: "Bosnia and Herzegovina",
    region: "Europe",
    coords: [17.8078, 43.3438],
    photos: [],
  },
  {
    id: "dubrovnik",
    name: "Dubrovnik",
    country: "Croatia",
    region: "Europe",
    coords: [18.0944, 42.6507],
    photos: [],
  },
  {
    id: "kotor",
    name: "Kotor",
    country: "Montenegro",
    region: "Europe",
    coords: [18.7712, 42.4247],
    photos: [],
  },
  {
    id: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    region: "North Africa",
    coords: [-7.9811, 31.6295],
    photos: [],
  },
  {
    id: "porto",
    name: "Porto",
    country: "Portugal",
    region: "Europe",
    coords: [-8.6291, 41.1579],
    photos: [],
  },
  {
    id: "aveiro",
    name: "Aveiro",
    country: "Portugal",
    region: "Europe",
    coords: [-8.6538, 40.6405],
    photos: [],
  },
  {
    id: "valencia",
    name: "Valencia",
    country: "Spain",
    region: "Europe",
    coords: [-0.3763, 39.4699],
    photos: [],
  },
  {
    id: "munich",
    name: "Munich",
    country: "Germany",
    region: "Europe",
    coords: [11.582, 48.1351],
    photos: [],
  },
  {
    id: "nuremberg",
    name: "Nuremberg",
    country: "Germany",
    region: "Europe",
    coords: [11.0767, 49.4521],
    photos: [],
  },
  {
    id: "galway",
    name: "Galway",
    country: "Ireland",
    region: "Europe",
    coords: [-9.0568, 53.2707],
    photos: [],
  },
  {
    id: "buenos-aires",
    name: "Buenos Aires",
    country: "Argentina",
    region: "South America",
    coords: [-58.3816, -34.6037],
    photos: [],
  },
  {
    id: "santiago",
    name: "Santiago",
    country: "Chile",
    region: "South America",
    coords: [-70.6693, -33.4489],
    photos: [],
  },
  {
    id: "valparaiso",
    name: "Valparaiso",
    country: "Chile",
    region: "South America",
    coords: [-71.6127, -33.0472],
    photos: [],
  },
  {
    id: "olmue",
    name: "Olmue",
    country: "Chile",
    region: "South America",
    coords: [-71.1867, -32.9958],
    photos: [],
  },
  {
    id: "montevideo",
    name: "Montevideo",
    country: "Uruguay",
    region: "South America",
    coords: [-56.1645, -34.9011],
    photos: [],
  },
  {
    id: "colonia-del-sacramento",
    name: "Colonia del Sacramento",
    country: "Uruguay",
    region: "South America",
    coords: [-57.8439, -34.4714],
    photos: [],
  },
  {
    id: "lima",
    name: "Lima",
    country: "Peru",
    region: "South America",
    coords: [-77.0428, -12.0464],
    photos: [],
  },
  {
    id: "cusco",
    name: "Cusco",
    country: "Peru",
    region: "South America",
    coords: [-71.9675, -13.5319],
    photos: [],
  },
  {
    id: "arequipa",
    name: "Arequipa",
    country: "Peru",
    region: "South America",
    coords: [-71.5375, -16.409],
    photos: [],
  },
  {
    id: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    region: "Southeast Asia",
    coords: [100.5018, 13.7563],
    photos: [],
  },
  {
    id: "siem-reap",
    name: "Siem Reap",
    country: "Cambodia",
    region: "Southeast Asia",
    coords: [103.8564, 13.3633],
    photos: [],
  },
  {
    id: "phnom-penh",
    name: "Phnom Penh",
    country: "Cambodia",
    region: "Southeast Asia",
    coords: [104.9282, 11.5564],
    photos: [],
  },
  {
    id: "ho-chi-minh-city",
    name: "Ho Chi Minh City",
    country: "Vietnam",
    region: "Southeast Asia",
    coords: [106.6297, 10.8231],
    photos: [],
  },
  {
    id: "ninh-binh",
    name: "Ninh Binh",
    country: "Vietnam",
    region: "Southeast Asia",
    coords: [105.9745, 20.2506],
    photos: [],
  },
  {
    id: "hoi-an",
    name: "Hoi An",
    country: "Vietnam",
    region: "Southeast Asia",
    coords: [108.338, 15.8801],
    photos: [],
  },
  {
    id: "hanoi",
    name: "Hanoi",
    country: "Vietnam",
    region: "Southeast Asia",
    coords: [105.8342, 21.0278],
    photos: [],
  },
];

export const ROUTE_SEGMENTS: RouteSegment[] = [
  { id: "dc-buenos-aires", origin: "washington-dc", destination: "buenos-aires", mode: "plane", month: "Dec 2024" },
  { id: "buenos-aires-santiago", origin: "buenos-aires", destination: "santiago", mode: "plane", month: "Jan 2025" },
  { id: "santiago-valparaiso", origin: "santiago", destination: "valparaiso", mode: "road", month: "Jan 2025" },
  { id: "valparaiso-olmue", origin: "valparaiso", destination: "olmue", mode: "road", month: "Jan 2025" },
  { id: "buenos-aires-montevideo", origin: "buenos-aires", destination: "montevideo", mode: "boat", month: "Jan 2025" },
  { id: "montevideo-colonia-del-sacramento", origin: "montevideo", destination: "colonia-del-sacramento", mode: "road", month: "Jan 2025" },
  { id: "santiago-dc", origin: "santiago", destination: "washington-dc", mode: "plane", month: "Jan 2025" },
  { id: "louisville-lima", origin: "louisville", destination: "lima", mode: "plane", month: "May 2025" },
  { id: "lima-cusco", origin: "lima", destination: "cusco", mode: "plane", month: "May 2025" },
  { id: "cusco-arequipa", origin: "cusco", destination: "arequipa", mode: "plane", month: "May 2025" },
  { id: "arequipa-lima", origin: "arequipa", destination: "lima", mode: "plane", month: "May 2025" },
  { id: "dc-madrid", origin: "washington-dc", destination: "madrid", mode: "plane", month: "Study abroad" },
  { id: "madrid-budapest", origin: "madrid", destination: "budapest", mode: "plane", month: "Study abroad" },
  { id: "madrid-edinburgh", origin: "madrid", destination: "edinburgh", mode: "plane", month: "Study abroad" },
  { id: "madrid-zurich", origin: "madrid", destination: "zurich", mode: "plane", month: "Study abroad" },
  { id: "zurich-st-anton", origin: "zurich", destination: "st-anton", mode: "train", month: "Study abroad" },
  { id: "madrid-lisbon", origin: "madrid", destination: "lisbon", mode: "plane", month: "Study abroad" },
  { id: "lisbon-sintra", origin: "lisbon", destination: "sintra", mode: "train", month: "Study abroad" },
  { id: "madrid-tirana", origin: "madrid", destination: "tirana", mode: "plane", month: "Study abroad" },
  { id: "tirana-berat", origin: "tirana", destination: "berat", mode: "road", month: "Study abroad" },
  { id: "madrid-dublin", origin: "madrid", destination: "dublin", mode: "plane", month: "Study abroad" },
  { id: "dublin-dingle", origin: "dublin", destination: "dingle", mode: "road", month: "Study abroad" },
  { id: "madrid-split", origin: "madrid", destination: "split", mode: "plane", month: "Study abroad" },
  { id: "split-mostar", origin: "split", destination: "mostar", mode: "road", month: "Study abroad" },
  { id: "mostar-dubrovnik", origin: "mostar", destination: "dubrovnik", mode: "road", month: "Study abroad" },
  { id: "dubrovnik-kotor", origin: "dubrovnik", destination: "kotor", mode: "road", month: "Study abroad" },
  { id: "kotor-madrid", origin: "kotor", destination: "madrid", mode: "plane", month: "Study abroad" },
  { id: "madrid-marrakech", origin: "madrid", destination: "marrakech", mode: "plane", month: "Study abroad" },
  { id: "madrid-porto", origin: "madrid", destination: "porto", mode: "plane", month: "Study abroad" },
  { id: "porto-aveiro", origin: "porto", destination: "aveiro", mode: "train", month: "Study abroad" },
  { id: "madrid-valencia", origin: "madrid", destination: "valencia", mode: "train", month: "Study abroad" },
  { id: "madrid-bilbao", origin: "madrid", destination: "bilbao", mode: "plane", month: "Study abroad" },
  { id: "madrid-salamanca", origin: "madrid", destination: "salamanca", mode: "train", month: "Study abroad" },
  { id: "madrid-segovia", origin: "madrid", destination: "segovia", mode: "train", month: "Study abroad" },
  { id: "madrid-toledo", origin: "madrid", destination: "toledo", mode: "road", month: "Study abroad" },
  { id: "dc-barcelona", origin: "washington-dc", destination: "barcelona", mode: "plane", month: "Summer 2023" },
  { id: "barcelona-marseille", origin: "barcelona", destination: "marseille", mode: "train", month: "Summer 2023" },
  { id: "marseille-antibes", origin: "marseille", destination: "antibes", mode: "train", month: "Summer 2023" },
  { id: "antibes-monaco", origin: "antibes", destination: "monaco", mode: "train", month: "Summer 2023" },
  { id: "antibes-bolzano", origin: "antibes", destination: "bolzano", mode: "train", month: "Summer 2023" },
  { id: "bolzano-venice", origin: "bolzano", destination: "venice", mode: "train", month: "Summer 2023" },
  { id: "venice-ljubljana", origin: "venice", destination: "ljubljana", mode: "train", month: "Summer 2023" },
  { id: "ljubljana-lake-bled", origin: "ljubljana", destination: "lake-bled", mode: "train", month: "Summer 2023" },
  { id: "ljubljana-zagreb", origin: "ljubljana", destination: "zagreb", mode: "train", month: "Summer 2023" },
  { id: "zagreb-dc", origin: "zagreb", destination: "washington-dc", mode: "plane", month: "Summer 2023" },
  { id: "dc-london", origin: "washington-dc", destination: "london", mode: "plane" },
  { id: "london-edinburgh", origin: "london", destination: "edinburgh", mode: "train" },
  { id: "edinburgh-st-andrews", origin: "edinburgh", destination: "st-andrews", mode: "road" },
  { id: "london-cambridge", origin: "london", destination: "cambridge", mode: "road" },
  { id: "dc-paris", origin: "washington-dc", destination: "paris", mode: "plane" },
  { id: "paris-versailles", origin: "paris", destination: "versailles", mode: "train" },
  { id: "dc-bangkok", origin: "washington-dc", destination: "bangkok", mode: "plane", month: "Summer 2024" },
  { id: "bangkok-siem-reap", origin: "bangkok", destination: "siem-reap", mode: "plane", month: "Summer 2024" },
  { id: "siem-reap-phnom-penh", origin: "siem-reap", destination: "phnom-penh", mode: "road", month: "Summer 2024" },
  { id: "phnom-penh-ho-chi-minh-city", origin: "phnom-penh", destination: "ho-chi-minh-city", mode: "plane", month: "Summer 2024" },
  { id: "ho-chi-minh-city-hoi-an", origin: "ho-chi-minh-city", destination: "hoi-an", mode: "plane", month: "Summer 2024" },
  { id: "hoi-an-ninh-binh", origin: "hoi-an", destination: "ninh-binh", mode: "road", month: "Summer 2024" },
  { id: "ninh-binh-hanoi", origin: "ninh-binh", destination: "hanoi", mode: "road", month: "Summer 2024" },
  { id: "hanoi-dc", origin: "hanoi", destination: "washington-dc", mode: "plane", month: "Summer 2024" },
  { id: "dc-chicago", origin: "washington-dc", destination: "chicago", mode: "plane" },
  { id: "dc-west-lafayette", origin: "washington-dc", destination: "west-lafayette", mode: "plane" },
  { id: "dc-boston", origin: "washington-dc", destination: "boston", mode: "road" },
  { id: "dc-indianapolis", origin: "washington-dc", destination: "indianapolis", mode: "plane" },
  { id: "indianapolis-west-lafayette", origin: "indianapolis", destination: "west-lafayette", mode: "road" },
  { id: "dc-castine", origin: "washington-dc", destination: "castine", mode: "road" },
  { id: "dc-corolla", origin: "washington-dc", destination: "corolla", mode: "road" },
  { id: "dc-hanover-nh", origin: "washington-dc", destination: "hanover-nh", mode: "road" },
  { id: "dc-deep-creek", origin: "washington-dc", destination: "deep-creek", mode: "road" },
  { id: "dc-north-conway", origin: "washington-dc", destination: "north-conway", mode: "road" },
  { id: "dc-seattle", origin: "washington-dc", destination: "seattle", mode: "plane" },
  { id: "dc-philadelphia", origin: "washington-dc", destination: "philadelphia", mode: "plane" },
  { id: "west-lafayette-nashville", origin: "west-lafayette", destination: "nashville", mode: "plane" },
  { id: "dc-louisville", origin: "washington-dc", destination: "louisville", mode: "plane" },
  { id: "west-lafayette-san-juan", origin: "west-lafayette", destination: "san-juan", mode: "plane" },
  { id: "louisville-seattle", origin: "louisville", destination: "seattle", mode: "plane" },
  { id: "dc-tampa", origin: "washington-dc", destination: "tampa", mode: "plane" },
  { id: "tampa-gainesville", origin: "tampa", destination: "gainesville", mode: "road" },
  { id: "west-lafayette-tampa", origin: "west-lafayette", destination: "tampa", mode: "plane" },
  { id: "louisville-tampa", origin: "louisville", destination: "tampa", mode: "plane" },
  { id: "madrid-munich", origin: "madrid", destination: "munich", mode: "plane" },
  { id: "munich-nuremberg", origin: "munich", destination: "nuremberg", mode: "train" },
  { id: "dingle-galway", origin: "dingle", destination: "galway", mode: "road" },
  { id: "galway-dublin", origin: "galway", destination: "dublin", mode: "road" },
  { id: "tampa-st. petersburg", origin: "tampa", destination: "st. petersburg", mode: "road" },
];

export const LOCATION_BY_ID = Object.fromEntries(LOCATIONS.map((location) => [location.id, location]));